### ISSUE TITLE
Email submission: CNAMEs in DNS

### ISSUE THREAD

**Issue by anthonybailey** [PauseAI/pauseai-collagen#10]
Copying message(s) to @joepio from  https://discord.com/channels/@me/1417934231312797768/1427291527222263929 Photo Petition thread @ into this issue.

I ~~may~~ need some technical help/permissions for one thing. Joep , how is the pauseai.info DNS configured? I would like to wire a couple of CNAMEs (sayno.pauseai.info and collagen.pauseai.info) to AWS addresses running services.

(First to validate emails and/or give permission to use them further, second for the collage building web app we enable later in the week.)

Unless we expose a naked IP, we do need sub domains working before we send emails.

Joep please advise, including whether anyone other than you has access?

**Comment by joepio** [comment]
Currently I manage nameservers through open provider. I suggest we migrate to netlify dns

**Comment by anthonybailey** [comment]
1. Ok, but "we" in "we migrate" is @joepio in practice, right? What's the timeline/risk management?

2. Can I ask you set some CNAMES pre-migration if it won't be quick?

For both questions: or are there suitably fine-grained permissions you can give credentials for so you don't have to be involved in each change?

**Comment by joepio** [comment]
Changed my mind: Cloudflare DNS is better than Netlify DNS for us:

1. Automated DNS record detection, which means less room for error and saves time
2. Free mutli-user setup, so you and nils can have your own accounts without monthly costs
3. DDOS prevention stuff (if the accelerationists want to take our site down)

I've sent you an invite, Anothony.

**Comment by anthonybailey** [comment]
Site currently is in "Finish setup" mode in Cloudflare for me. I know we may have to wait longer. But next steps, and assignment?

**Comment by joepio** [comment]
Seems like it's ready / active now. Next step: you edit the DNS settings. And maybe invite nils?

**Comment by anthonybailey** [comment]
Oh ok dig +trace is giving me
> NS      agustin.ns.cloudflare.com

So I guess it works before you choose your plan. Less surprising.

I'll confirm free. Because otherwise I think this blocks further changes.

**Comment by anthonybailey** [comment]
Nah, this still looks wrong. My view of the domain still claims proxying is unactivated even though the docs says this occurs by default.

The page warns:

Records we found:

8 A


4 AAAA


7 MX


6 TXT


Our scan may have missed uncommon records or custom subdomains. Compare the list below to your current DNS provider (most likely your registrar) and add any missing records. Pay close attention to all records on the zone apex, records of the type A, AAAA, and CNAME and records needed for email like MX, SPF, DMARC, DKIM, and MTA-STS.

I see none of the (imported?) A records use certificates.

Confused.

@joepio please confirm whether you see the same?

**Comment by joepio** [comment]
I've just now removed old ns records (which cloudflare ironically imported), maybe that confused some things. I just checked, I think all records are there.

**Comment by danilupion** [comment]
Hi!

For what is worth, making the record not proxied should fix the issue (but you lose some of the benefits you are interested in -eg: DDoS-)

![Screenshot_20251019-201736.png](https://github.com/user-attachments/assets/e02b6834-6fbc-4662-b852-61d5d78a8b7a)

**Comment by anthonybailey** [comment]
I'm really sorry, @joepio , but I still can't.

My user in Cloudinary dashboard continues to see "Last step: Update your nameservers to activate Cloudflare" for the domain, an "Invalid nameservers" warning everywhere, and no controls since confirming the free plan.

I am *assuming* this is not what you see. Please confirm?

**Comment by anthonybailey** [comment]
Yay! Technology! :picard:

Logging out, clearing cookies, and logging back in did fix it.

**Comment by anthonybailey** [comment]
@danilupion I have paused the CloudFlare interception, so unless the terrible interference denies using them as a DNS provider too we should be good. Let me know?

**Comment by danilupion** [comment]
Apologies, did not see that comment until now and the blockage is no longer active, I guess we will have to wait until next weekend to validate, thanks!

**Comment by danilupion** [comment]
Hi team,

Just letting you know issue is back (matching days & hours in which the blockage seems to be applied)

![Screenshot_20251025-193025.png](https://github.com/user-attachments/assets/891ae62e-1c7a-4e54-8d3b-54a28126f471)
